#ifndef _MSGDEF_H
#define _MSGDEF_H


/////////////////////  KARIKAT  <-------->  KARIKAT_Eye

#define NOTI_KARIKAT_ON 0x300
#define REQ_KARIKAT_EYE_REGISTER 0x400
#define ANS_KARIKAT_EYE_REGISTER 0x301
#define NOTI_TARGET_TRACKING_INFO 0x401
#define CMD_START_SEND_IMG 0x302
#define CMD_STOP_SEND_IMG 0x303



//////////////////// KARIKAT   <------->    GroundControl

#define MSG_ID_CN_NOTI_SAY_HELLO					(0x140)
#define MSG_ID_NC_REQ_REGISTER						(0x210)
#define MSG_ID_CN_ACK_REQ_REGISTER					(0x120)
#define MSG_ID_NC_REQ_ALIVE							(0x211)
#define MSG_ID_CN_ACK_REQ_ALIVE						(0x121)
#define MSG_ID_NC_NOTI_AHRS_ALIVE					(0x240)
#define MSG_ID_NC_NOTI_LIDAR_VALUE					(0x241)
#define MSG_ID_CN_REQ_CHANGE_MODE					(0x110)
#define MSG_ID_NC_ACK_REQ_CHANGE_MODE				(0x220)
#define MSG_ID_CN_REQ_SET_PARAMETER					(0x111)
#define MSG_ID_NC_ACK_REQ_SET_PARAMETER				(0x221)
#define MSG_ID_CN_CMD_THRUST_CONTROL_VALUE			(0x141)
#define MSG_ID_CN_CMD_LOW_AIR_BEARING_CONTROL_VALUE	(0x142)
#define MSG_ID_CN_CMD_REACTION_WHEEL_CONTROL_VALUE	(0x143)
#define MSG_ID_CN_CMD_HIGH_AIR_BEARING_CONTROL_VALUE (0x144)
#define MSG_ID_CN_CMD_MOTOR_CONTROL_VALUE			(0x145)
#define MSG_ID_CN_REQ_CHANGE_MISSION_SCENARIO		(0x112)
#define MSG_ID_NC_ACK_REQ_CHANGE_MISSION_SCENARIO	(0x222)
#define MSG_ID_NC_NOTI_MISSION_STATE_CHANGE			(0x242)
#define MSG_ID_CN_REQ_START_MISSION					(0x113)
#define MSG_ID_NC_ACK_REQ_START_MISSION				(0x223)
#define MSG_ID_CN_REQ_STOP_MISSION					(0x114)
#define MSG_ID_NC_ACK_REQ_STOP_MISSION				(0x224)
#define MSG_ID_CN_CMD_CONTROL_NODE					(0x146)
#define MSG_ID_NC_NOTI_CAMERA_VALUE					(0x243)
#define MSG_ID_CN_REQ_MANUAL_CONTROL				(0x115)
#define MSG_ID_NC_ACK_REQ_MANUAL_CONTROL			(0x225)

#define REQ_MSG 0x010
#define ACK_MSG 0x020
#define CMD_NOTI_MSG 0x040
#define NC_MSG 0x200
#define CN_MSG 0x100


#endif
